### ISSUE TITLE
Grab  forcefield from URL

### ISSUE THREAD

**Issue by mikemhenry** [openmm/openmmforcefields#276] opened 2023-06-13 16:35 UTC

**Comment by mikemhenry** [comment] 2023-06-13 16:42
A user should be able to specify a URL (maybe look at using cloudbpathlib  so the URL could be to a S3 bucket) to retrieve a openff forecefield xml. We should optionally support supplying a hash of the file for data integrity checks.

**Comment by jchodera** [comment] 2023-06-13 20:47
Duplicate of #267.

**Closed by jchodera** 2023-06-13 20:47 UTC
